php:
  preset: laravel
  disabled:
    - no_unused_imports
  enabled:
    - heredoc_indentation
    - trailing_comma_in_multiline_call
  finder:
    not-name:
      - index.php
      - server.php
css: true
