blank_issues_enabled: false
contact_links:
    - name: Get Help
      url: https://laravelmaroc.com/forum/new-thread
      about: If you need help with your project create a topic on our forum.
    - name: Bug Report
      url: https://github.com/laravelmorocco/laravelmaroc.com/issues/new
      about: 'For projects issues, suggest changes on our issues repository.'
    - name: Feature Request
      url: https://github.com/laravelmorocco/laravelmaroc.com/discussions/new?category=ideas
      about: Share ideas for new features
